#include <jni.h>
#include <string>
extern "C" {
JNIEXPORT jstring JNICALL Java_com_connectstudios_connect_vpn_SimpleVpnService_tunnelConfig(
        JNIEnv *env,
        jobject /* this */) {
    std::string hello = """{\n"
                        "  \"dns\": {\n"
                        "    \"hosts\": {\n"
                        "      \"domain:googleapis.cn\": \"googleapis.com\"\n"
                        "    },\n"
                        "    \"servers\": [\n"
                        "      \"1.1.1.1\"\n"
                        "    ]\n"
                        "  },\n"
                        "  \"inbounds\": [\n"
                        "    {\n"
                        "      \"port\": 10808,\n"
                        "      \"protocol\": \"socks\",\n"
                        "      \"settings\": {\n"
                        "        \"auth\": \"noauth\",\n"
                        "        \"udp\": true,\n"
                        "        \"userLevel\": 8\n"
                        "      },\n"
                        "      \"sniffing\": {\n"
                        "        \"destOverride\": [\n"
                        "          \"http\",\n"
                        "          \"tls\"\n"
                        "        ],\n"
                        "        \"enabled\": false\n"
                        "      },\n"
                        "      \"tag\": \"socks\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"port\": 10809,\n"
                        "      \"protocol\": \"http\",\n"
                        "      \"settings\": {\n"
                        "        \"userLevel\": 8\n"
                        "      },\n"
                        "      \"tag\": \"http\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"listen\": \"127.0.0.1\",\n"
                        "      \"port\": 10807,\n"
                        "      \"protocol\": \"dokodemo-door\",\n"
                        "      \"settings\": {\n"
                        "        \"address\": \"1.1.1.1\",\n"
                        "        \"network\": \"tcp,udp\",\n"
                        "        \"port\": 53\n"
                        "      },\n"
                        "      \"tag\": \"dns-in\"\n"
                        "    }\n"
                        "  ],\n"
                        "  \"log\": {\n"
                        "    \"loglevel\": \"warning\"\n"
                        "  },\n"
                        "  \"outbounds\": [\n"
                        "    {\n"
                        "      \"mux\": {\n"
                        "        \"enabled\": false\n"
                        "      },\n"
                        "      \"protocol\": \"vmess\",\n"
                        "      \"settings\": {\n"
                        "        \"vnext\": [\n"
                        "          {\n"
                        "            \"address\": \"ex.euginex.cf\",\n"
                        "            \"port\": 443,\n"
                        "            \"users\": [\n"
                        "              {\n"
                        "                \"alterId\": 0,\n"
                        "                \"id\": \"a5a9aa29-9938-4d0f-84b0-6205e0d7816e\",\n"
                        "                \"level\": 8,\n"
                        "                \"security\": \"auto\"\n"
                        "              }\n"
                        "            ]\n"
                        "          }\n"
                        "        ]\n"
                        "      },\n"
                        "      \"streamSettings\": {\n"
                        "        \"network\": \"ws\",\n"
                        "        \"security\": \"tls\",\n"
                        "        \"tlsSettings\": {\n"
                        "          \"allowInsecure\": true,\n"
                        "          \"serverName\": \"mutindo.euginex.cf\"\n"
                        "        },\n"
                        "        \"wsSettings\": {\n"
                        "          \"headers\": {\n"
                        "            \"Host\": \"mutindo.euginex.cf\"\n"
                        "          },\n"
                        "          \"path\": \"/\"\n"
                        "        }\n"
                        "      },\n"
                        "      \"tag\": \"proxy\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"protocol\": \"freedom\",\n"
                        "      \"settings\": {},\n"
                        "      \"tag\": \"direct\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"protocol\": \"blackhole\",\n"
                        "      \"settings\": {\n"
                        "        \"response\": {\n"
                        "          \"type\": \"http\"\n"
                        "        }\n"
                        "      },\n"
                        "      \"tag\": \"block\"\n"
                        "    },\n"
                        "    {\n"
                        "      \"protocol\": \"dns\",\n"
                        "      \"tag\": \"dns-out\"\n"
                        "    }\n"
                        "  ],\n"
                        "  \"policy\": {\n"
                        "    \"levels\": {\n"
                        "      \"8\": {\n"
                        "        \"connIdle\": 300,\n"
                        "        \"downlinkOnly\": 1,\n"
                        "        \"handshake\": 4,\n"
                        "        \"uplinkOnly\": 1\n"
                        "      }\n"
                        "    },\n"
                        "    \"system\": {\n"
                        "      \"statsOutboundUplink\": true,\n"
                        "      \"statsOutboundDownlink\": true\n"
                        "    }\n"
                        "  },\n"
                        "  \"routing\": {\n"
                        "    \"domainStrategy\": \"IPIfNonMatch\",\n"
                        "    \"rules\": [\n"
                        "      {\n"
                        "        \"inboundTag\": [\n"
                        "          \"dns-in\"\n"
                        "        ],\n"
                        "        \"outboundTag\": \"dns-out\",\n"
                        "        \"type\": \"field\"\n"
                        "      },\n"
                        "      {\n"
                        "        \"ip\": [\n"
                        "          \"1.1.1.1\"\n"
                        "        ],\n"
                        "        \"outboundTag\": \"proxy\",\n"
                        "        \"port\": \"53\",\n"
                        "        \"type\": \"field\"\n"
                        "      },\n"
                        "      {\n"
                        "        \"ip\": [\n"
                        "          \"1.1.1.1\"\n"
                        "        ],\n"
                        "        \"outboundTag\": \"direct\",\n"
                        "        \"port\": \"53\",\n"
                        "        \"type\": \"field\"\n"
                        "      }\n"
                        "    ]\n"
                        "  },\n"
                        "  \"stats\": {}\n"
                        "}""";
    return env->NewStringUTF(hello.c_str());
}

JNIEXPORT jstring JNICALL Java_com_connectstudios_connect_ConnectTunnel_sshServerAddress(
        JNIEnv *env,
        jobject /* this */) {
    std::string sshServerAddress = "51.81.80.126";
    return env->NewStringUTF(sshServerAddress.c_str());
}

JNIEXPORT jint JNICALL Java_com_connectstudios_connect_ConnectTunnel_sshServerPort(
        JNIEnv *env,
        jobject /* this */) {
    int sshServerPort =80;
    return (sshServerPort);
}

JNIEXPORT jstring JNICALL Java_com_connectstudios_connect_ConnectTunnel_appName(
        JNIEnv *env,
        jobject /* this */) {
    std::string appName = "OneV";
    return env->NewStringUTF(appName.c_str());
}

}
